export enum ErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_EMAIL = "INVALID_EMAIL",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  EMAIL_IN_USE = "EMAIL_IN_USE",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  CONNECTION_ERROR = "CONNECTION_ERROR",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  DATABASE_ERROR = "DATABASE_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
}
